# permissions for end users to view istioadaptiverequestoptimizers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: istio-adaptive-least-request
    app.kubernetes.io/managed-by: kustomize
  name: istioadaptiverequestoptimizer-viewer-role
rules:
- apiGroups:
  - optimization.liorfranko.github.io
  resources:
  - istioadaptiverequestoptimizers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - optimization.liorfranko.github.io
  resources:
  - istioadaptiverequestoptimizers/status
  verbs:
  - get
